name: Build Release
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "23 23 * * 0"
jobs:
  build:
    permissions: 
      issues: write
      pull-requests: write
      security-events: write
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    env:
      ENDOR_NAMESPACE: "yolo"
    steps:
      - name: Clone Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
      - name: Setup JDK with Maven
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: microsoft
          java-version: 17
      
      - name: Build release package
        run: mvn -B clean install

      - name: Endor Labs Scan
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: endorlabs/github-action@02231267f2d7d3be21f10662fdd39fba143d4bda # v1.1.9
        with:
          namespace: ${{ env.ENDOR_NAMESPACE }}
          pr: "false"
          sarif_file: endor-labs.sarif
          additional_args: "--output-type=summary"
          
      - name: Endor Labs Scan PR to Default Branch
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@02231267f2d7d3be21f10662fdd39fba143d4bda # v1.1.9
        with:
          namespace: ${{ env.ENDOR_NAMESPACE }}
          pr: true
          enable_pr_comments: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sarif_file: endor-labs.sarif
          additional_args: "--output-type=summary"

      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9
        with:
          sarif_file: endor-labs.sarif

      - name: Dockerize
        id: dockerbuild
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          docker build . -t endorlabs/hearts_github
          echo "image_id=endorlabs/hearts_github@$(docker inspect --format {{.ID}} endorlabs/hearts_github)" >> "$GITHUB_OUTPUT"

      - name: Sign Docker Image with Endor Labs
        if: ${{ steps.dockerbuild.outcome == 'success' }}
        uses: endorlabs/github-action/sign@02231267f2d7d3be21f10662fdd39fba143d4bda # v1.1.9
        with:
          namespace: ${{ env.ENDOR_NAMESPACE }}
          artifact_name: ${{ steps.dockerbuild.outputs.image_id }}
      
      # PUBLISH IMAGE HERE -- avoiding due to demo repo
        
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: endorlabs-java-webapp-demo
          path: |
            target/endor-java-webapp-demo.jar
        
      
